Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
JWT:
  Secret: Axbros
  Issuer: Nuite
  Expire: 7200
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: zawx0422  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: blog-service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Host: 127.0.0.1:6379
  Password:
  MaxIdle: 30
  MaxActive: 30
  IdleTimeout: 200
